steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
      '-t',
      'gcr.io/$PROJECT_ID/backend2:$SHORT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
      'gcr.io/$PROJECT_ID/backend2:$SHORT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'backend2', '--image', 'gcr.io/$PROJECT_ID/backend2:$SHORT_SHA', 
        '--region', 'asia-southeast2', '--allow-unauthenticated']

images:
  - gcr.io/$PROJECT_ID/backend2:$SHORT_SHA