###ADD USER 
POST http://localhost:8383/adduser
Content-Type: application/json
{
    "name": "avee",
    "password": "yolo",
    "age": 34
}


###ADD UPDATE 
POST http://localhost:8383/update
Content-Type: application/json
{
    "id": "wtts4Mb87tZk0uQ1xYoX",
    "name": "avees"
}
